apiVersion: v1
kind: Service
metadata:
  name: ivolve-svc
  namespace: ivolve
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # make it public
spec:
  type: LoadBalancer
  selector:
    app: ivolve
  ports:
    - port: 80
      targetPort: 5000
